#!/bin/sh -e
#
# Run the pass container
#
# Usage: run [ VAULT-DIR ]
#

CONTAINER="ghcr.io/perfsonar/docker-pass:latest"

die()
{
    echo "$@" 1>&2
    exit 1
}

[ $# -le 1 ] \
    || die "Usage: $(basename $0) [ VAULT_DIR ]"

if [ -n "$1" ]
then
    [ -d "$1" ] \
	|| die "$1: Not a directory."
    VAULT_VOL="--volume '$1:/vault'"
fi

docker run -it --rm \
       --pull always \
       --volume "${HOME}:/vol/home" \
       ${VAULT_VOL} \
       "${CONTAINER}" \
       "$(getent passwd $(id -nu))"
