#!/bin/sh -e
#
# Run the pass container
#
# Usage: run VAULT-DIR
#

CONTAINER="ghcr.io/perfsonar/docker-pass:latest"


die()
{
    echo "$@" 1>&2
    exit 1
}


[ $# -eq 1 ] \
    || die "Usage: $(basename $0) VAULT_DIR"

[ -d "$1" ] \
    || die "$1: Not a directory."


# Get a password entry by name in a portable way
# Args:
#  1 - User name
getent_passwd()
{
    case "$(uname -s)" in

        Darwin)
            dscacheutil -q user -a name "$1" \
                | sed -e 's/^[^ ]*: //' \
                | tr '\n' ':' \
                | awk -F ':' '{ print $1":"$2":"$3":"$4":"$7":"$5":"$6 }'
            ;;

        *)
            getent passwd "$1"
            ;;

    esac
}


run_container()
{

    exec docker run -it --rm \
	   --name "pass-$(date +%s)" \
	   --hostname "pass" \
	   --pull always \
	   --volume "${HOME}:/vol/home" \
	   "$@" \
	   "${CONTAINER}" \
	   "$(getent_passwd $(id -nu))"
}

[ -z "$1" ] \
    && run_container \
    || run_container --volume "$1:/vault"
